#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jun 08, 2022 04:14:12 PM -03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import Telas

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = Telas.Login(_top1)
    # Creates a toplevel widget.
    global _top2, _w2
    _top2 = tk.Toplevel(root)
    _w2 = Telas.Menu(_top2)
    # Creates a toplevel widget.
    global _top3, _w3
    _top3 = tk.Toplevel(root)
    _w3 = Telas.Cadastro(_top3)
    # Creates a toplevel widget.
    global _top4, _w4
    _top4 = tk.Toplevel(root)
    _w4 = Telas.Deposito(_top4)
    # Creates a toplevel widget.
    global _top8, _w8
    _top8 = tk.Toplevel(root)
    _w8 = Telas.Saque(_top8)
    # Creates a toplevel widget.
    global _top9, _w9
    _top9 = tk.Toplevel(root)
    _w9 = Telas.Extrato(_top9)
    root.mainloop()

if __name__ == '__main__':
    Telas.start_up()




