# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CadastroCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastroCliente(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 501, 501))
        font = QtGui.QFont()
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setStyleSheet("background-image: url(CadastroCliente.png);")
        self.label.setLineWidth(0)
        self.label.setText("")
        self.label.setObjectName("label")
        self.name = QtWidgets.QTextEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(168, 50, 265, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name.setFont(font)
        self.name.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.name.setObjectName("name")
        self.cpf = QtWidgets.QTextEdit(self.centralwidget)
        self.cpf.setGeometry(QtCore.QRect(168, 101, 265, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cpf.setFont(font)
        self.cpf.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.cpf.setObjectName("cpf")
        self.telefone = QtWidgets.QTextEdit(self.centralwidget)
        self.telefone.setGeometry(QtCore.QRect(168, 152, 265, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.telefone.setFont(font)
        self.telefone.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.telefone.setObjectName("telefone")
        self.address = QtWidgets.QTextEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(168, 203, 265, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.address.setFont(font)
        self.address.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.address.setObjectName("address")
        self.overdraft = QtWidgets.QTextEdit(self.centralwidget)
        self.overdraft.setGeometry(QtCore.QRect(168, 307, 265, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.overdraft.setFont(font)
        self.overdraft.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.overdraft.setObjectName("overdraft")
        self.password = QtWidgets.QTextEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(168, 359, 265, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.password.setObjectName("password")
        self.tipodeconta = QtWidgets.QComboBox(self.centralwidget)
        self.tipodeconta.setGeometry(QtCore.QRect(168, 256, 263, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tipodeconta.setFont(font)
        self.tipodeconta.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.tipodeconta.setObjectName("tipodeconta")
        self.tipodeconta.addItem("")
        self.tipodeconta.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 427, 155, 46))
        self.pushButton.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Banco Assemble"))
        self.name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.cpf.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
        self.tipodeconta.setItemText(0, _translate("MainWindow", "CORRENTE"))
        self.tipodeconta.setItemText(1, _translate("MainWindow", "POUPANÇA"))
        self.pushButton.setText(_translate("MainWindow", "CADASTRAR"))

