# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CadastroFuncionario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CadastroFuncionario(object):
    def setupUi(self, CadastroFuncionario):
        CadastroFuncionario.setObjectName("CadastroFuncionario")
        CadastroFuncionario.resize(500, 500)
        CadastroFuncionario.setMinimumSize(QtCore.QSize(500, 500))
        CadastroFuncionario.setMaximumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(CadastroFuncionario)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-2, -5, 501, 511))
        self.label.setStyleSheet("background-image: url(CadastroFuncionario.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 434, 157, 47))
        self.pushButton.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.pushButton.setObjectName("pushButton")
        self.name = QtWidgets.QTextEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(180, 43, 218, 36))
        self.name.setMaximumSize(QtCore.QSize(218, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name.setFont(font)
        self.name.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.name.setObjectName("name")
        self.agency = QtWidgets.QTextEdit(self.centralwidget)
        self.agency.setGeometry(QtCore.QRect(180, 87, 218, 36))
        self.agency.setMaximumSize(QtCore.QSize(218, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.agency.setFont(font)
        self.agency.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.agency.setObjectName("agency")
        self.role = QtWidgets.QTextEdit(self.centralwidget)
        self.role.setGeometry(QtCore.QRect(180, 129, 218, 36))
        self.role.setMaximumSize(QtCore.QSize(218, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.role.setFont(font)
        self.role.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.role.setObjectName("role")
        self.cpf = QtWidgets.QTextEdit(self.centralwidget)
        self.cpf.setGeometry(QtCore.QRect(180, 171, 218, 36))
        self.cpf.setMaximumSize(QtCore.QSize(218, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cpf.setFont(font)
        self.cpf.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.cpf.setObjectName("cpf")
        self.number = QtWidgets.QTextEdit(self.centralwidget)
        self.number.setGeometry(QtCore.QRect(180, 215, 218, 36))
        self.number.setMaximumSize(QtCore.QSize(218, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.number.setFont(font)
        self.number.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.number.setObjectName("number")
        self.address = QtWidgets.QTextEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(180, 258, 218, 36))
        self.address.setMaximumSize(QtCore.QSize(218, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.address.setFont(font)
        self.address.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.address.setObjectName("address")
        self.overdraft = QtWidgets.QTextEdit(self.centralwidget)
        self.overdraft.setGeometry(QtCore.QRect(180, 343, 218, 36))
        self.overdraft.setMaximumSize(QtCore.QSize(218, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.overdraft.setFont(font)
        self.overdraft.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.overdraft.setObjectName("overdraft")
        self.password = QtWidgets.QTextEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(180, 386, 218, 36))
        self.password.setMaximumSize(QtCore.QSize(218, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.password.setObjectName("password")
        self.tipodeconta = QtWidgets.QComboBox(self.centralwidget)
        self.tipodeconta.setGeometry(QtCore.QRect(180, 300, 219, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tipodeconta.setFont(font)
        self.tipodeconta.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.tipodeconta.setObjectName("tipodeconta")
        self.tipodeconta.addItem("")
        self.tipodeconta.addItem("")
        CadastroFuncionario.setCentralWidget(self.centralwidget)

        self.retranslateUi(CadastroFuncionario)
        QtCore.QMetaObject.connectSlotsByName(CadastroFuncionario)

    def retranslateUi(self, CadastroFuncionario):
        _translate = QtCore.QCoreApplication.translate
        CadastroFuncionario.setWindowTitle(_translate("CadastroFuncionario", "Banco Assemble"))
        self.pushButton.setText(_translate("CadastroFuncionario", "CADASTRAR"))
        self.name.setHtml(_translate("CadastroFuncionario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.agency.setHtml(_translate("CadastroFuncionario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.role.setHtml(_translate("CadastroFuncionario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.cpf.setHtml(_translate("CadastroFuncionario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.number.setHtml(_translate("CadastroFuncionario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.address.setHtml(_translate("CadastroFuncionario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.overdraft.setHtml(_translate("CadastroFuncionario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.password.setHtml(_translate("CadastroFuncionario", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tipodeconta.setItemText(0, _translate("CadastroFuncionario", "CORRENTE"))
        self.tipodeconta.setItemText(1, _translate("CadastroFuncionario", "POUPANÇA"))

