# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deposito.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QWidget
from requests import request
import RequestDeposit
import sessao
class MainClass(QWidget):
    def __init__(self,text):
        super().__init__()
        self.text = text

    def clickMethod(self):
        QMessageBox.about(self, "Deposito", self.text)


class Ui_Deposito(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 100)
        MainWindow.setMinimumSize(QtCore.QSize(400, 100))
        MainWindow.setMaximumSize(QtCore.QSize(400, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 401, 121))
        self.label.setStyleSheet("background-image: url(Deposit.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 58, 60, 34))
        self.pushButton.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 58, 60, 34))
        self.pushButton_2.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(100, 20, 201, 31))
        font = QtGui.QFont()
        self.close = MainWindow.close()
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.textEdit.setObjectName("textEdit")
        self.conta = QtWidgets.QTextEdit(self.centralwidget)
        self.conta.setGeometry(QtCore.QRect(30, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.conta.setFont(font)
        self.conta.setStyleSheet("background-color: rgb(238, 186, 43);")
        self.conta.setObjectName("conta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton.clicked.connect(lambda: self.informacoes(self.conta.toPlainText(),self.textEdit.toPlainText()))
        self.pushButton_2.clicked.connect(lambda: MainWindow.close())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def informacoes(self,conta,valor):
        try:
            RequestDeposit.deposit(sessao.sessao['token'],conta,valor)
            MainClass('Deposito Realizado com Sucesso').clickMethod()
        except Exception as e:
            MainClass('Erro:'+str(e)).clickMethod()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Deposito"))
        self.pushButton.setText(_translate("MainWindow", "Deposite"))
        self.pushButton_2.setText(_translate("MainWindow", "Voltar"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
        self.conta.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
