#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jun 12, 2022 09:45:56 AM -03  platform: Windows NT

import tkinter as tk
import sys
import tkinter.ttk as ttk
from tkinter.constants import *

import Login_support

class Inicio:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("400x300")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Banco Assemble")
        top.configure(background="#d9d9d9")

        self.top = top

        self.Initial = tk.Frame(self.top)
        self.Initial.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Initial.configure(relief='groove')
        self.Initial.configure(borderwidth="2")
        self.Initial.configure(relief="groove")
        self.Initial.configure(background="#ffffff")

        self.Administrador = tk.Button(self.Initial)
        self.Administrador.place(relx=0.625, rely=0.7, height=74, width=147)
        self.Administrador.configure(activebackground="beige")
        self.Administrador.configure(activeforeground="#000000")
        self.Administrador.configure(background="#ffff80")
        self.Administrador.configure(compound='left')
        self.Administrador.configure(disabledforeground="#a3a3a3")
        self.Administrador.configure(font="-family {Times New Roman} -size 9 -weight bold")
        self.Administrador.configure(foreground="#000000")
        self.Administrador.configure(highlightbackground="#d9d9d9")
        self.Administrador.configure(highlightcolor="black")
        photo_location = "app\escolhamoduloegressos_icone.gif"
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Administrador.configure(image=_img0)
        self.Administrador.configure(pady="0")
        self.Administrador.configure(text='''Diretor''')

        self.Cliente = tk.Button(self.Initial)
        self.Cliente.place(relx=0.625, rely=0.033, height=74, width=147)
        self.Cliente.configure(activebackground="beige")
        self.Cliente.configure(activeforeground="#ffffff")
        self.Cliente.configure(background="#ffff80")
        self.Cliente.configure(compound='left')
        self.Cliente.configure(disabledforeground="#a3a3a3")
        self.Cliente.configure(font="-family {Times New Roman} -size 9 -weight bold")
        self.Cliente.configure(foreground="#000000")
        self.Cliente.configure(highlightbackground="#d9d9d9")
        self.Cliente.configure(highlightcolor="black")
        photo_location = "app\escolhamoduloalunos_icone.gif"
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.Cliente.configure(image=_img1)
        self.Cliente.configure(pady="0")
        self.Cliente.configure(text='''Cliente''')

        self.Gerente = tk.Button(self.Initial)
        self.Gerente.place(relx=0.625, rely=0.367, height=74, width=147)
        self.Gerente.configure(activebackground="beige")
        self.Gerente.configure(activeforeground="#000000")
        self.Gerente.configure(background="#ffff80")
        self.Gerente.configure(compound='left')
        self.Gerente.configure(disabledforeground="#a3a3a3")
        self.Gerente.configure(font="-family {Times New Roman} -size 9 -weight bold")
        self.Gerente.configure(foreground="#000000")
        self.Gerente.configure(highlightbackground="#d9d9d9")
        self.Gerente.configure(highlightcolor="black")
        photo_location = "app\escolhamodulopais_aluno_icone.gif"
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.Gerente.configure(image=_img2)
        self.Gerente.configure(pady="0")
        self.Gerente.configure(text='''Gerente''')

        self.Logo = tk.Label(self.Initial)
        self.Logo.place(relx=-0.025, rely=-0.067, height=331, width=254)
        self.Logo.configure(activebackground="#004080")
        self.Logo.configure(activeforeground="white")
        self.Logo.configure(anchor='w')
        self.Logo.configure(background="#000000")
        self.Logo.configure(compound='left')
        self.Logo.configure(cursor="fleur")
        self.Logo.configure(disabledforeground="#a3a3a3")
        self.Logo.configure(foreground="#000000")
        photo_location = "app\output-onlinepngtools (1).png"
        global _img3
        _img3 = tk.PhotoImage(file=photo_location)
        self.Logo.configure(image=_img3)

class PadraoLogin:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("600x450+381+120")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Login Cliente")
        top.configure(background="#d9d9d9")

        self.top = top

        self.FrameCliente = tk.Frame(self.top)
        self.FrameCliente.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.FrameCliente.configure(relief='groove')
        self.FrameCliente.configure(borderwidth="2")
        self.FrameCliente.configure(relief="groove")
        self.FrameCliente.configure(background="#ffffff")

        self.Logo = tk.Label(self.FrameCliente)
        self.Logo.place(relx=-0.017, rely=0.0, height=451, width=454)
        self.Logo.configure(activebackground="#ffffff")
        self.Logo.configure(anchor='w')
        self.Logo.configure(background="#000080")
        self.Logo.configure(compound='left')
        self.Logo.configure(disabledforeground="#a3a3a3")
        self.Logo.configure(font="-family {Times New Roman} -size 22 -underline 1")
        self.Logo.configure(foreground="#000000")
        photo_location = "app\logo.png"
        global _img4
        _img4 = tk.PhotoImage(file=photo_location)
        self.Logo.configure(image=_img4)

        self.Cadastrar = tk.Button(self.FrameCliente)
        self.Cadastrar.place(relx=0.8, rely=0.511, height=24, width=77)
        self.Cadastrar.configure(activebackground="beige")
        self.Cadastrar.configure(activeforeground="#000000")
        self.Cadastrar.configure(background="#d9d9d9")
        self.Cadastrar.configure(compound='left')
        self.Cadastrar.configure(disabledforeground="#a3a3a3")
        self.Cadastrar.configure(foreground="#000000")
        self.Cadastrar.configure(highlightbackground="#d9d9d9")
        self.Cadastrar.configure(highlightcolor="black")
        self.Cadastrar.configure(pady="0")
        self.Cadastrar.configure(text='''Cadastrar''')
        #self.cadastrar.configure(command= 'app.cadastrar')

        self.Login = tk.Button(self.FrameCliente)
        self.Login.place(relx=0.8, rely=0.422, height=24, width=77)
        self.Login.configure(activebackground="beige")
        self.Login.configure(activeforeground="#000000")
        self.Login.configure(background="#d9d9d9")
        self.Login.configure(compound='left')
        self.Login.configure(disabledforeground="#a3a3a3")
        self.Login.configure(foreground="#000000")
        self.Login.configure(highlightbackground="#d9d9d9")
        self.Login.configure(highlightcolor="black")
        self.Login.configure(pady="0")
        self.Login.configure(text='''Login''')
        #self.login.configure(command= )
        

        self.Usuario = tk.Entry(self.FrameCliente)
        self.Usuario.place(relx=0.767, rely=0.178, height=20, relwidth=0.207)
        self.Usuario.configure(background="white")
        self.Usuario.configure(disabledforeground="#a3a3a3")
        self.Usuario.configure(font="TkFixedFont")
        self.Usuario.configure(foreground="#000000")
        self.Usuario.configure(insertbackground="black")

        self.Senha = tk.Entry(self.FrameCliente)
        self.Senha.place(relx=0.767, rely=0.333, height=20, relwidth=0.207)
        self.Senha.configure(background="white")
        self.Senha.configure(disabledforeground="#a3a3a3")
        self.Senha.configure(font="TkFixedFont")
        self.Senha.configure(foreground="#000000")
        self.Senha.configure(insertbackground="black")

        self.Label1 = tk.Label(self.FrameCliente)
        self.Label1.place(relx=0.833, rely=0.267, height=21, width=44)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Senha''')

        self.Label1 = tk.Label(self.FrameCliente)
        self.Label1.place(relx=0.833, rely=0.111, height=21, width=54)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Usuario''')

class PadraoLogin_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("600x450+382+119")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Login Gerente")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.FrameAdm = tk.Frame(self.top)
        self.FrameAdm.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.FrameAdm.configure(relief='groove')
        self.FrameAdm.configure(borderwidth="2")
        self.FrameAdm.configure(relief="groove")
        self.FrameAdm.configure(background="#ffffff")
        self.FrameAdm.configure(highlightbackground="#d9d9d9")
        self.FrameAdm.configure(highlightcolor="black")

        self.Logo = tk.Label(self.FrameAdm)
        self.Logo.place(relx=-0.017, rely=0.0, height=451, width=454)
        self.Logo.configure(activebackground="#ffffff")
        self.Logo.configure(anchor='w')
        self.Logo.configure(background="#000080")
        self.Logo.configure(compound='left')
        self.Logo.configure(disabledforeground="#a3a3a3")
        self.Logo.configure(font="-family {Times New Roman} -size 22 -underline 1")
        self.Logo.configure(foreground="#000000")
        self.Logo.configure(highlightbackground="#d9d9d9")
        self.Logo.configure(highlightcolor="black")
        photo_location = "app\logo.png"
        global _img5
        _img5 = tk.PhotoImage(file=photo_location)
        self.Logo.configure(image=_img5)

        self.Login = tk.Button(self.FrameAdm)
        self.Login.place(relx=0.8, rely=0.422, height=24, width=77)
        self.Login.configure(activebackground="beige")
        self.Login.configure(activeforeground="#000000")
        self.Login.configure(background="#d9d9d9")
        self.Login.configure(compound='left')
        self.Login.configure(disabledforeground="#a3a3a3")
        self.Login.configure(foreground="#000000")
        self.Login.configure(highlightbackground="#d9d9d9")
        self.Login.configure(highlightcolor="black")
        self.Login.configure(pady="0")
        self.Login.configure(text='''Login''')

        self.Usuario = tk.Entry(self.FrameAdm)
        self.Usuario.place(relx=0.767, rely=0.178, height=20, relwidth=0.207)
        self.Usuario.configure(background="white")
        self.Usuario.configure(disabledforeground="#a3a3a3")
        self.Usuario.configure(font="TkFixedFont")
        self.Usuario.configure(foreground="#000000")
        self.Usuario.configure(highlightbackground="#d9d9d9")
        self.Usuario.configure(highlightcolor="black")
        self.Usuario.configure(insertbackground="black")
        self.Usuario.configure(selectbackground="#c4c4c4")
        self.Usuario.configure(selectforeground="black")

        self.Senha = tk.Entry(self.FrameAdm)
        self.Senha.place(relx=0.767, rely=0.333, height=20, relwidth=0.207)
        self.Senha.configure(background="white")
        self.Senha.configure(disabledforeground="#a3a3a3")
        self.Senha.configure(font="TkFixedFont")
        self.Senha.configure(foreground="#000000")
        self.Senha.configure(highlightbackground="#d9d9d9")
        self.Senha.configure(highlightcolor="black")
        self.Senha.configure(insertbackground="black")
        self.Senha.configure(selectbackground="#c4c4c4")
        self.Senha.configure(selectforeground="black")

        self.Label1 = tk.Label(self.FrameAdm)
        self.Label1.place(relx=0.833, rely=0.267, height=21, width=44)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Senha''')

        self.Label1 = tk.Label(self.FrameAdm)
        self.Label1.place(relx=0.833, rely=0.111, height=21, width=54)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Usuario''')

class LoginADM:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = 'gray40' # X11 color: #666666
        _ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
        _ana2color = 'beige' # X11 color: #f5f5dc
        _tabfg1 = 'black' 
        _tabfg2 = 'black' 
        _tabbg1 = 'grey75' 
        _tabbg2 = 'grey89' 
        _bgmode = 'light' 

        top.geometry("600x450+332+169")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Login Gerente")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.FrameGerente = tk.Frame(self.top)
        self.FrameGerente.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.FrameGerente.configure(relief='groove')
        self.FrameGerente.configure(borderwidth="2")
        self.FrameGerente.configure(relief="groove")
        self.FrameGerente.configure(background="#ffffff")
        self.FrameGerente.configure(highlightbackground="#d9d9d9")
        self.FrameGerente.configure(highlightcolor="black")

        self.Logo = tk.Label(self.FrameGerente)
        self.Logo.place(relx=-0.017, rely=0.0, height=451, width=454)
        self.Logo.configure(activebackground="#ffffff")
        self.Logo.configure(anchor='w')
        self.Logo.configure(background="#000080")
        self.Logo.configure(compound='left')
        self.Logo.configure(disabledforeground="#a3a3a3")
        self.Logo.configure(font="-family {Times New Roman} -size 22 -underline 1")
        self.Logo.configure(foreground="#000000")
        self.Logo.configure(highlightbackground="#d9d9d9")
        self.Logo.configure(highlightcolor="black")
        photo_location = "app\logo.png"
        global _img6
        _img6 = tk.PhotoImage(file=photo_location)
        self.Logo.configure(image=_img6)

        self.Login = tk.Button(self.FrameGerente)
        self.Login.place(relx=0.8, rely=0.422, height=24, width=77)
        self.Login.configure(activebackground="beige")
        self.Login.configure(activeforeground="#000000")
        self.Login.configure(background="#d9d9d9")
        self.Login.configure(compound='left')
        self.Login.configure(disabledforeground="#a3a3a3")
        self.Login.configure(foreground="#000000")
        self.Login.configure(highlightbackground="#d9d9d9")
        self.Login.configure(highlightcolor="black")
        self.Login.configure(pady="0")
        self.Login.configure(text='''Login''')

        self.Usuario = tk.Entry(self.FrameGerente)
        self.Usuario.place(relx=0.767, rely=0.178, height=20, relwidth=0.207)
        self.Usuario.configure(background="white")
        self.Usuario.configure(disabledforeground="#a3a3a3")
        self.Usuario.configure(font="TkFixedFont")
        self.Usuario.configure(foreground="#000000")
        self.Usuario.configure(highlightbackground="#d9d9d9")
        self.Usuario.configure(highlightcolor="black")
        self.Usuario.configure(insertbackground="black")
        self.Usuario.configure(selectbackground="#c4c4c4")
        self.Usuario.configure(selectforeground="black")

        self.Senha = tk.Entry(self.FrameGerente)
        self.Senha.place(relx=0.767, rely=0.333, height=20, relwidth=0.207)
        self.Senha.configure(background="white")
        self.Senha.configure(disabledforeground="#a3a3a3")
        self.Senha.configure(font="TkFixedFont")
        self.Senha.configure(foreground="#000000")
        self.Senha.configure(highlightbackground="#d9d9d9")
        self.Senha.configure(highlightcolor="black")
        self.Senha.configure(insertbackground="black")
        self.Senha.configure(selectbackground="#c4c4c4")
        self.Senha.configure(selectforeground="black")

        self.Label1 = tk.Label(self.FrameGerente)
        self.Label1.place(relx=0.833, rely=0.267, height=21, width=44)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Senha''')

        self.Label1 = tk.Label(self.FrameGerente)
        self.Label1.place(relx=0.833, rely=0.111, height=21, width=44)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Usuario''')

def start_up():
    Login_support.main()

if __name__ == '__main__':
    Login_support.main()